package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class AppAppInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.ID
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.APP_CODE
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.APP_NAME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.APP_URL
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String appUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.NAME_KEY
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String nameKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.PASS_KEY
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String passKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.SSO_ACTION
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String ssoAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.CREATE_TIME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.MODIFY_TIME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.DELETED
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.DESCRIPTION
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.IS_SHOW
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_app_info.SORT
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.ID
     *
     * @return the value of app_app_info.ID
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.ID
     *
     * @param id the value for app_app_info.ID
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.APP_CODE
     *
     * @return the value of app_app_info.APP_CODE
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.APP_CODE
     *
     * @param appCode the value for app_app_info.APP_CODE
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.APP_NAME
     *
     * @return the value of app_app_info.APP_NAME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.APP_NAME
     *
     * @param appName the value for app_app_info.APP_NAME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.APP_URL
     *
     * @return the value of app_app_info.APP_URL
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.APP_URL
     *
     * @param appUrl the value for app_app_info.APP_URL
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.NAME_KEY
     *
     * @return the value of app_app_info.NAME_KEY
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getNameKey() {
        return nameKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.NAME_KEY
     *
     * @param nameKey the value for app_app_info.NAME_KEY
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.PASS_KEY
     *
     * @return the value of app_app_info.PASS_KEY
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getPassKey() {
        return passKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.PASS_KEY
     *
     * @param passKey the value for app_app_info.PASS_KEY
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setPassKey(String passKey) {
        this.passKey = passKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.SSO_ACTION
     *
     * @return the value of app_app_info.SSO_ACTION
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getSsoAction() {
        return ssoAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.SSO_ACTION
     *
     * @param ssoAction the value for app_app_info.SSO_ACTION
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setSsoAction(String ssoAction) {
        this.ssoAction = ssoAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.CREATE_TIME
     *
     * @return the value of app_app_info.CREATE_TIME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.CREATE_TIME
     *
     * @param createTime the value for app_app_info.CREATE_TIME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.MODIFY_TIME
     *
     * @return the value of app_app_info.MODIFY_TIME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.MODIFY_TIME
     *
     * @param modifyTime the value for app_app_info.MODIFY_TIME
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.DELETED
     *
     * @return the value of app_app_info.DELETED
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.DELETED
     *
     * @param deleted the value for app_app_info.DELETED
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.DESCRIPTION
     *
     * @return the value of app_app_info.DESCRIPTION
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.DESCRIPTION
     *
     * @param description the value for app_app_info.DESCRIPTION
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.IS_SHOW
     *
     * @return the value of app_app_info.IS_SHOW
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.IS_SHOW
     *
     * @param isShow the value for app_app_info.IS_SHOW
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_app_info.SORT
     *
     * @return the value of app_app_info.SORT
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_app_info.SORT
     *
     * @param sort the value for app_app_info.SORT
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}