package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class AppMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.parent_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_code
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.menu_order
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.permission_key
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String permissionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.target
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.show_style
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String showStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_menu.app_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long appId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.id
     *
     * @return the value of app_menu.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.id
     *
     * @param id the value for app_menu.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.parent_id
     *
     * @return the value of app_menu.parent_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.parent_id
     *
     * @param parentId the value for app_menu.parent_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_code
     *
     * @return the value of app_menu.menu_code
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_code
     *
     * @param menuCode the value for app_menu.menu_code
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_name
     *
     * @return the value of app_menu.menu_name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_name
     *
     * @param menuName the value for app_menu.menu_name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.menu_order
     *
     * @return the value of app_menu.menu_order
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.menu_order
     *
     * @param menuOrder the value for app_menu.menu_order
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.permission_key
     *
     * @return the value of app_menu.permission_key
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getPermissionKey() {
        return permissionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.permission_key
     *
     * @param permissionKey the value for app_menu.permission_key
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setPermissionKey(String permissionKey) {
        this.permissionKey = permissionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.target
     *
     * @return the value of app_menu.target
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.target
     *
     * @param target the value for app_menu.target
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.description
     *
     * @return the value of app_menu.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.description
     *
     * @param description the value for app_menu.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.show_style
     *
     * @return the value of app_menu.show_style
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getShowStyle() {
        return showStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.show_style
     *
     * @param showStyle the value for app_menu.show_style
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setShowStyle(String showStyle) {
        this.showStyle = showStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.create_time
     *
     * @return the value of app_menu.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.create_time
     *
     * @param createTime the value for app_menu.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.modify_time
     *
     * @return the value of app_menu.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.modify_time
     *
     * @param modifyTime the value for app_menu.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_menu.app_id
     *
     * @return the value of app_menu.app_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_menu.app_id
     *
     * @param appId the value for app_menu.app_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }
}