package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.AuJobInfo;
import com.dassmeta.passport.dal.dataobject.AuJobInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuJobInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(AuJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(AuJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(AuJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(AuJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<AuJobInfo> selectByExample(AuJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    AuJobInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuJobInfo record, @Param("example") AuJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") AuJobInfo record, @Param("example") AuJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(AuJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_job_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(AuJobInfo record);
}