package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.AuOrgInfo;
import com.dassmeta.passport.dal.dataobject.AuOrgInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuOrgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(AuOrgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(AuOrgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(AuOrgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(AuOrgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<AuOrgInfo> selectByExample(AuOrgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    AuOrgInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuOrgInfo record, @Param("example") AuOrgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") AuOrgInfo record, @Param("example") AuOrgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(AuOrgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_org_info
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(AuOrgInfo record);
}