package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class AuOrgInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.parent_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.org_name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.id_full_path
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String idFullPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.org_code
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.ordering
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Integer ordering;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.contacter
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String contacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.contact_phone
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_org_info.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.id
     *
     * @return the value of au_org_info.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.id
     *
     * @param id the value for au_org_info.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.parent_id
     *
     * @return the value of au_org_info.parent_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.parent_id
     *
     * @param parentId the value for au_org_info.parent_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.org_name
     *
     * @return the value of au_org_info.org_name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.org_name
     *
     * @param orgName the value for au_org_info.org_name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.id_full_path
     *
     * @return the value of au_org_info.id_full_path
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getIdFullPath() {
        return idFullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.id_full_path
     *
     * @param idFullPath the value for au_org_info.id_full_path
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setIdFullPath(String idFullPath) {
        this.idFullPath = idFullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.org_code
     *
     * @return the value of au_org_info.org_code
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.org_code
     *
     * @param orgCode the value for au_org_info.org_code
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.ordering
     *
     * @return the value of au_org_info.ordering
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Integer getOrdering() {
        return ordering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.ordering
     *
     * @param ordering the value for au_org_info.ordering
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.contacter
     *
     * @return the value of au_org_info.contacter
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getContacter() {
        return contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.contacter
     *
     * @param contacter the value for au_org_info.contacter
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setContacter(String contacter) {
        this.contacter = contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.contact_phone
     *
     * @return the value of au_org_info.contact_phone
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.contact_phone
     *
     * @param contactPhone the value for au_org_info.contact_phone
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.description
     *
     * @return the value of au_org_info.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.description
     *
     * @param description the value for au_org_info.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.create_time
     *
     * @return the value of au_org_info.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.create_time
     *
     * @param createTime the value for au_org_info.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.modify_time
     *
     * @return the value of au_org_info.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.modify_time
     *
     * @param modifyTime the value for au_org_info.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_org_info.deleted
     *
     * @return the value of au_org_info.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_org_info.deleted
     *
     * @param deleted the value for au_org_info.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }
}