package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.AuUser;
import com.dassmeta.passport.dal.dataobject.AuUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(AuUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(AuUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(AuUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(AuUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<AuUser> selectByExample(AuUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    AuUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuUser record, @Param("example") AuUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") AuUser record, @Param("example") AuUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(AuUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(AuUser record);
}