package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class AuUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.login_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.password
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.vpn_group
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String vpnGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.type
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.id
     *
     * @return the value of au_user.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.id
     *
     * @param id the value for au_user.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.login_id
     *
     * @return the value of au_user.login_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.login_id
     *
     * @param loginId the value for au_user.login_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.password
     *
     * @return the value of au_user.password
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.password
     *
     * @param password the value for au_user.password
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.deleted
     *
     * @return the value of au_user.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.deleted
     *
     * @param deleted the value for au_user.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.create_time
     *
     * @return the value of au_user.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.create_time
     *
     * @param createTime the value for au_user.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.modify_time
     *
     * @return the value of au_user.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.modify_time
     *
     * @param modifyTime the value for au_user.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.vpn_group
     *
     * @return the value of au_user.vpn_group
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getVpnGroup() {
        return vpnGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.vpn_group
     *
     * @param vpnGroup the value for au_user.vpn_group
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setVpnGroup(String vpnGroup) {
        this.vpnGroup = vpnGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.type
     *
     * @return the value of au_user.type
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.type
     *
     * @param type the value for au_user.type
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }
}