package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.AuUserDetail;
import com.dassmeta.passport.dal.dataobject.AuUserDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuUserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(AuUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(AuUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(AuUserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(AuUserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<AuUserDetail> selectByExample(AuUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    AuUserDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuUserDetail record, @Param("example") AuUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") AuUserDetail record, @Param("example") AuUserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(AuUserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table au_user_detail
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(AuUserDetail record);
}