package com.dassmeta.passport.dal.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DictionaryAreacodeRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public DictionaryAreacodeRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeIsNull() {
            addCriterion("ORIGINAL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeIsNotNull() {
            addCriterion("ORIGINAL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeEqualTo(String value) {
            addCriterion("ORIGINAL_CODE =", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeNotEqualTo(String value) {
            addCriterion("ORIGINAL_CODE <>", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeGreaterThan(String value) {
            addCriterion("ORIGINAL_CODE >", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORIGINAL_CODE >=", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeLessThan(String value) {
            addCriterion("ORIGINAL_CODE <", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeLessThanOrEqualTo(String value) {
            addCriterion("ORIGINAL_CODE <=", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeLike(String value) {
            addCriterion("ORIGINAL_CODE like", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeNotLike(String value) {
            addCriterion("ORIGINAL_CODE not like", value, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeIn(List<String> values) {
            addCriterion("ORIGINAL_CODE in", values, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeNotIn(List<String> values) {
            addCriterion("ORIGINAL_CODE not in", values, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeBetween(String value1, String value2) {
            addCriterion("ORIGINAL_CODE between", value1, value2, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalCodeNotBetween(String value1, String value2) {
            addCriterion("ORIGINAL_CODE not between", value1, value2, "originalCode");
            return (Criteria) this;
        }

        public Criteria andOriginalNameIsNull() {
            addCriterion("ORIGINAL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOriginalNameIsNotNull() {
            addCriterion("ORIGINAL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalNameEqualTo(String value) {
            addCriterion("ORIGINAL_NAME =", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameNotEqualTo(String value) {
            addCriterion("ORIGINAL_NAME <>", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameGreaterThan(String value) {
            addCriterion("ORIGINAL_NAME >", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORIGINAL_NAME >=", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameLessThan(String value) {
            addCriterion("ORIGINAL_NAME <", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameLessThanOrEqualTo(String value) {
            addCriterion("ORIGINAL_NAME <=", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameLike(String value) {
            addCriterion("ORIGINAL_NAME like", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameNotLike(String value) {
            addCriterion("ORIGINAL_NAME not like", value, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameIn(List<String> values) {
            addCriterion("ORIGINAL_NAME in", values, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameNotIn(List<String> values) {
            addCriterion("ORIGINAL_NAME not in", values, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameBetween(String value1, String value2) {
            addCriterion("ORIGINAL_NAME between", value1, value2, "originalName");
            return (Criteria) this;
        }

        public Criteria andOriginalNameNotBetween(String value1, String value2) {
            addCriterion("ORIGINAL_NAME not between", value1, value2, "originalName");
            return (Criteria) this;
        }

        public Criteria andNowCodeIsNull() {
            addCriterion("NOW_CODE is null");
            return (Criteria) this;
        }

        public Criteria andNowCodeIsNotNull() {
            addCriterion("NOW_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andNowCodeEqualTo(String value) {
            addCriterion("NOW_CODE =", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeNotEqualTo(String value) {
            addCriterion("NOW_CODE <>", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeGreaterThan(String value) {
            addCriterion("NOW_CODE >", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeGreaterThanOrEqualTo(String value) {
            addCriterion("NOW_CODE >=", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeLessThan(String value) {
            addCriterion("NOW_CODE <", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeLessThanOrEqualTo(String value) {
            addCriterion("NOW_CODE <=", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeLike(String value) {
            addCriterion("NOW_CODE like", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeNotLike(String value) {
            addCriterion("NOW_CODE not like", value, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeIn(List<String> values) {
            addCriterion("NOW_CODE in", values, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeNotIn(List<String> values) {
            addCriterion("NOW_CODE not in", values, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeBetween(String value1, String value2) {
            addCriterion("NOW_CODE between", value1, value2, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowCodeNotBetween(String value1, String value2) {
            addCriterion("NOW_CODE not between", value1, value2, "nowCode");
            return (Criteria) this;
        }

        public Criteria andNowNameIsNull() {
            addCriterion("NOW_NAME is null");
            return (Criteria) this;
        }

        public Criteria andNowNameIsNotNull() {
            addCriterion("NOW_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNowNameEqualTo(String value) {
            addCriterion("NOW_NAME =", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameNotEqualTo(String value) {
            addCriterion("NOW_NAME <>", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameGreaterThan(String value) {
            addCriterion("NOW_NAME >", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameGreaterThanOrEqualTo(String value) {
            addCriterion("NOW_NAME >=", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameLessThan(String value) {
            addCriterion("NOW_NAME <", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameLessThanOrEqualTo(String value) {
            addCriterion("NOW_NAME <=", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameLike(String value) {
            addCriterion("NOW_NAME like", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameNotLike(String value) {
            addCriterion("NOW_NAME not like", value, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameIn(List<String> values) {
            addCriterion("NOW_NAME in", values, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameNotIn(List<String> values) {
            addCriterion("NOW_NAME not in", values, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameBetween(String value1, String value2) {
            addCriterion("NOW_NAME between", value1, value2, "nowName");
            return (Criteria) this;
        }

        public Criteria andNowNameNotBetween(String value1, String value2) {
            addCriterion("NOW_NAME not between", value1, value2, "nowName");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("OPERATOR =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("OPERATOR <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("OPERATOR >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("OPERATOR <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("OPERATOR like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("OPERATOR not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("OPERATOR in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("OPERATOR not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("OPERATOR between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("OPERATOR not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeIsNull() {
            addCriterion("OPERATOR_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeIsNotNull() {
            addCriterion("OPERATOR_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeEqualTo(Date value) {
            addCriterionForJDBCDate("OPERATOR_TIME =", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("OPERATOR_TIME <>", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("OPERATOR_TIME >", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OPERATOR_TIME >=", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeLessThan(Date value) {
            addCriterionForJDBCDate("OPERATOR_TIME <", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OPERATOR_TIME <=", value, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeIn(List<Date> values) {
            addCriterionForJDBCDate("OPERATOR_TIME in", values, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("OPERATOR_TIME not in", values, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OPERATOR_TIME between", value1, value2, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperatorTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OPERATOR_TIME not between", value1, value2, "operatorTime");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNull() {
            addCriterion("OPERATION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIsNotNull() {
            addCriterion("OPERATION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTypeEqualTo(String value) {
            addCriterion("OPERATION_TYPE =", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotEqualTo(String value) {
            addCriterion("OPERATION_TYPE <>", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThan(String value) {
            addCriterion("OPERATION_TYPE >", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATION_TYPE >=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThan(String value) {
            addCriterion("OPERATION_TYPE <", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLessThanOrEqualTo(String value) {
            addCriterion("OPERATION_TYPE <=", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeLike(String value) {
            addCriterion("OPERATION_TYPE like", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotLike(String value) {
            addCriterion("OPERATION_TYPE not like", value, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeIn(List<String> values) {
            addCriterion("OPERATION_TYPE in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotIn(List<String> values) {
            addCriterion("OPERATION_TYPE not in", values, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeBetween(String value1, String value2) {
            addCriterion("OPERATION_TYPE between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andOperationTypeNotBetween(String value1, String value2) {
            addCriterion("OPERATION_TYPE not between", value1, value2, "operationType");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("NOTES is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("NOTES is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("NOTES =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("NOTES <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("NOTES >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("NOTES >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("NOTES <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("NOTES <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("NOTES like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("NOTES not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("NOTES in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("NOTES not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("NOTES between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("NOTES not between", value1, value2, "notes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 19 13:52:34 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dictionary_areacode_record
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}