package com.dassmeta.passport.dal.dataobject;

public class DictionaryIntegration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_integration.ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_integration.PARENT_ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_integration.NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_integration.CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_integration.VALUE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_integration.STATE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_integration.ID
     *
     * @return the value of dictionary_integration.ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_integration.ID
     *
     * @param id the value for dictionary_integration.ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_integration.PARENT_ID
     *
     * @return the value of dictionary_integration.PARENT_ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_integration.PARENT_ID
     *
     * @param parentId the value for dictionary_integration.PARENT_ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_integration.NAME
     *
     * @return the value of dictionary_integration.NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_integration.NAME
     *
     * @param name the value for dictionary_integration.NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_integration.CODE
     *
     * @return the value of dictionary_integration.CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_integration.CODE
     *
     * @param code the value for dictionary_integration.CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_integration.VALUE
     *
     * @return the value of dictionary_integration.VALUE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_integration.VALUE
     *
     * @param value the value for dictionary_integration.VALUE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_integration.STATE
     *
     * @return the value of dictionary_integration.STATE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_integration.STATE
     *
     * @param state the value for dictionary_integration.STATE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }
}