package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class DictionaryAreacodeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.ORIGINAL_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String originalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.ORIGINAL_NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String originalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.NOW_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String nowCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.NOW_NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String nowName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.OPERATOR
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.OPERATOR_TIME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private Date operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.OPERATION_TYPE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode_record.NOTES
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.ID
     *
     * @return the value of dictionary_areacode_record.ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.ID
     *
     * @param id the value for dictionary_areacode_record.ID
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.ORIGINAL_CODE
     *
     * @return the value of dictionary_areacode_record.ORIGINAL_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getOriginalCode() {
        return originalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.ORIGINAL_CODE
     *
     * @param originalCode the value for dictionary_areacode_record.ORIGINAL_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setOriginalCode(String originalCode) {
        this.originalCode = originalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.ORIGINAL_NAME
     *
     * @return the value of dictionary_areacode_record.ORIGINAL_NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getOriginalName() {
        return originalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.ORIGINAL_NAME
     *
     * @param originalName the value for dictionary_areacode_record.ORIGINAL_NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.NOW_CODE
     *
     * @return the value of dictionary_areacode_record.NOW_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getNowCode() {
        return nowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.NOW_CODE
     *
     * @param nowCode the value for dictionary_areacode_record.NOW_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setNowCode(String nowCode) {
        this.nowCode = nowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.NOW_NAME
     *
     * @return the value of dictionary_areacode_record.NOW_NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getNowName() {
        return nowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.NOW_NAME
     *
     * @param nowName the value for dictionary_areacode_record.NOW_NAME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setNowName(String nowName) {
        this.nowName = nowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.OPERATOR
     *
     * @return the value of dictionary_areacode_record.OPERATOR
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.OPERATOR
     *
     * @param operator the value for dictionary_areacode_record.OPERATOR
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.OPERATOR_TIME
     *
     * @return the value of dictionary_areacode_record.OPERATOR_TIME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.OPERATOR_TIME
     *
     * @param operatorTime the value for dictionary_areacode_record.OPERATOR_TIME
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.OPERATION_TYPE
     *
     * @return the value of dictionary_areacode_record.OPERATION_TYPE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.OPERATION_TYPE
     *
     * @param operationType the value for dictionary_areacode_record.OPERATION_TYPE
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode_record.NOTES
     *
     * @return the value of dictionary_areacode_record.NOTES
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode_record.NOTES
     *
     * @param notes the value for dictionary_areacode_record.NOTES
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}