package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.DictionaryIntegration;
import com.dassmeta.passport.dal.dataobject.DictionaryIntegrationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryIntegrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int countByExample(DictionaryIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int deleteByExample(DictionaryIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int insert(DictionaryIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int insertSelective(DictionaryIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    List<DictionaryIntegration> selectByExample(DictionaryIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    DictionaryIntegration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") DictionaryIntegration record, @Param("example") DictionaryIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int updateByExample(@Param("record") DictionaryIntegration record, @Param("example") DictionaryIntegrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int updateByPrimaryKeySelective(DictionaryIntegration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_integration
     *
     * @mbggenerated Thu Jan 19 13:52:34 CST 2017
     */
    int updateByPrimaryKey(DictionaryIntegration record);
}