package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class DictionaryAreacode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.ID
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.AREA_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.PROVINCE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.CITY
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.COUNTY
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.TOWN
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.VILLAGE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String village;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.STREET
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.NOTE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.STATE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_areacode.OPERATE_TIME
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.ID
     *
     * @return the value of dictionary_areacode.ID
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.ID
     *
     * @param id the value for dictionary_areacode.ID
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.AREA_CODE
     *
     * @return the value of dictionary_areacode.AREA_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.AREA_CODE
     *
     * @param areaCode the value for dictionary_areacode.AREA_CODE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.PROVINCE
     *
     * @return the value of dictionary_areacode.PROVINCE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.PROVINCE
     *
     * @param province the value for dictionary_areacode.PROVINCE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.CITY
     *
     * @return the value of dictionary_areacode.CITY
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.CITY
     *
     * @param city the value for dictionary_areacode.CITY
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.COUNTY
     *
     * @return the value of dictionary_areacode.COUNTY
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.COUNTY
     *
     * @param county the value for dictionary_areacode.COUNTY
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.TOWN
     *
     * @return the value of dictionary_areacode.TOWN
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.TOWN
     *
     * @param town the value for dictionary_areacode.TOWN
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setTown(String town) {
        this.town = town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.VILLAGE
     *
     * @return the value of dictionary_areacode.VILLAGE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.VILLAGE
     *
     * @param village the value for dictionary_areacode.VILLAGE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setVillage(String village) {
        this.village = village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.STREET
     *
     * @return the value of dictionary_areacode.STREET
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.STREET
     *
     * @param street the value for dictionary_areacode.STREET
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.NOTE
     *
     * @return the value of dictionary_areacode.NOTE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.NOTE
     *
     * @param note the value for dictionary_areacode.NOTE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.STATE
     *
     * @return the value of dictionary_areacode.STATE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.STATE
     *
     * @param state the value for dictionary_areacode.STATE
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_areacode.OPERATE_TIME
     *
     * @return the value of dictionary_areacode.OPERATE_TIME
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_areacode.OPERATE_TIME
     *
     * @param operateTime the value for dictionary_areacode.OPERATE_TIME
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}