package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.DictionaryAreacode;
import com.dassmeta.passport.dal.dataobject.DictionaryAreacodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryAreacodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int countByExample(DictionaryAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int deleteByExample(DictionaryAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int insert(DictionaryAreacode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int insertSelective(DictionaryAreacode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    List<DictionaryAreacode> selectByExample(DictionaryAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    DictionaryAreacode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") DictionaryAreacode record, @Param("example") DictionaryAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int updateByExample(@Param("record") DictionaryAreacode record, @Param("example") DictionaryAreacodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int updateByPrimaryKeySelective(DictionaryAreacode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_areacode
     *
     * @mbggenerated Thu Jan 19 13:52:33 CST 2017
     */
    int updateByPrimaryKey(DictionaryAreacode record);
}