package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class UrpPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.permission_key
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String permissionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.permission_type
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_permission.app_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long appId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.id
     *
     * @return the value of urp_permission.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.id
     *
     * @param id the value for urp_permission.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.name
     *
     * @return the value of urp_permission.name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.name
     *
     * @param name the value for urp_permission.name
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.permission_key
     *
     * @return the value of urp_permission.permission_key
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getPermissionKey() {
        return permissionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.permission_key
     *
     * @param permissionKey the value for urp_permission.permission_key
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setPermissionKey(String permissionKey) {
        this.permissionKey = permissionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.permission_type
     *
     * @return the value of urp_permission.permission_type
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.permission_type
     *
     * @param permissionType the value for urp_permission.permission_type
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.description
     *
     * @return the value of urp_permission.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.description
     *
     * @param description the value for urp_permission.description
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.create_time
     *
     * @return the value of urp_permission.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.create_time
     *
     * @param createTime the value for urp_permission.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.modify_time
     *
     * @return the value of urp_permission.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.modify_time
     *
     * @param modifyTime the value for urp_permission.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.deleted
     *
     * @return the value of urp_permission.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.deleted
     *
     * @param deleted the value for urp_permission.deleted
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_permission.app_id
     *
     * @return the value of urp_permission.app_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_permission.app_id
     *
     * @param appId the value for urp_permission.app_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }
}