package com.dassmeta.passport.dal.dataobject;

import java.util.Date;

public class UrpRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_role_permission.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_role_permission.role_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_role_permission.permission_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_role_permission.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urp_role_permission.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_role_permission.id
     *
     * @return the value of urp_role_permission.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_role_permission.id
     *
     * @param id the value for urp_role_permission.id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_role_permission.role_id
     *
     * @return the value of urp_role_permission.role_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_role_permission.role_id
     *
     * @param roleId the value for urp_role_permission.role_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_role_permission.permission_id
     *
     * @return the value of urp_role_permission.permission_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_role_permission.permission_id
     *
     * @param permissionId the value for urp_role_permission.permission_id
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_role_permission.create_time
     *
     * @return the value of urp_role_permission.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_role_permission.create_time
     *
     * @param createTime the value for urp_role_permission.create_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urp_role_permission.modify_time
     *
     * @return the value of urp_role_permission.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urp_role_permission.modify_time
     *
     * @param modifyTime the value for urp_role_permission.modify_time
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}