package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.UrpRolePermission;
import com.dassmeta.passport.dal.dataobject.UrpRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrpRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(UrpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(UrpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(UrpRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(UrpRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<UrpRolePermission> selectByExample(UrpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    UrpRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") UrpRolePermission record, @Param("example") UrpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") UrpRolePermission record, @Param("example") UrpRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(UrpRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(UrpRolePermission record);
}