package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.UrpRole;
import com.dassmeta.passport.dal.dataobject.UrpRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrpRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(UrpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(UrpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(UrpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(UrpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<UrpRole> selectByExample(UrpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    UrpRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") UrpRole record, @Param("example") UrpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") UrpRole record, @Param("example") UrpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(UrpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(UrpRole record);
}