package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.UrpUserRole;
import com.dassmeta.passport.dal.dataobject.UrpUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrpUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(UrpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(UrpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(UrpUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(UrpUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<UrpUserRole> selectByExample(UrpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    UrpUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") UrpUserRole record, @Param("example") UrpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") UrpUserRole record, @Param("example") UrpUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(UrpUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_role
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(UrpUserRole record);
}