package com.dassmeta.passport.dal.dataobject;

import com.dassmeta.passport.dal.dataobject.UrpUserPermission;
import com.dassmeta.passport.dal.dataobject.UrpUserPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrpUserPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int countByExample(UrpUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByExample(UrpUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insert(UrpUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int insertSelective(UrpUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    List<UrpUserPermission> selectByExample(UrpUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    UrpUserPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") UrpUserPermission record, @Param("example") UrpUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByExample(@Param("record") UrpUserPermission record, @Param("example") UrpUserPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKeySelective(UrpUserPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urp_user_permission
     *
     * @mbggenerated Thu Jan 19 13:57:36 CST 2017
     */
    int updateByPrimaryKey(UrpUserPermission record);
}